dependencies:
  - python=3.9
  - matplotlib
  # - networkx
  - numpy
  - pandas
  - scipy
  # # - tqdm==4.46.0
  # - watermark
  - python-wget
  - shapely
  - Cartopy==0.18.0
  - statsmodels
  - netcdf4
  - xarray
  - zarr
  - openpyxl
  - jupyter=1.0.0
  - Bottleneck=1.3.2
  - dask=2021.9.1
  - climlab=0.7.12
  - pip
  - libstdcxx-ng=12.1.0
  - pip:
    - pyleoclim==0.8.0
    - pylr2 


